// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Obs_Project;

#nullable disable

namespace Obs_Project.Migrations
{
    [DbContext(typeof(ObsDbContext))]
    partial class ObsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Obs_Project.Dersler", b =>
                {
                    b.Property<int>("DersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersId"));

                    b.Property<string>("DersAd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<int>("DersKod")
                        .HasColumnType("int");

                    b.HasKey("DersId");

                    b.ToTable("Ders");
                });

            modelBuilder.Entity("Obs_Project.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("Numara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SinifID")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.HasKey("OgrenciID");

                    b.HasIndex("SinifID");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("Obs_Project.OgrenciDers", b =>
                {
                    b.Property<int>("OgrenciID")
                        .HasColumnType("int");

                    b.Property<int>("DersID")
                        .HasColumnType("int");

                    b.HasKey("OgrenciID", "DersID");

                    b.HasIndex("DersID");

                    b.ToTable("OgrenciDers");
                });

            modelBuilder.Entity("Obs_Project.Siniflar", b =>
                {
                    b.Property<int>("SinifID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SinifID"));

                    b.Property<string>("Kontenjan")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar");

                    b.Property<string>("SinifAd")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.HasKey("SinifID");

                    b.ToTable("Siniflar");
                });

            modelBuilder.Entity("Obs_Project.Ogrenci", b =>
                {
                    b.HasOne("Obs_Project.Siniflar", "Siniflar")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("SinifID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siniflar");
                });

            modelBuilder.Entity("Obs_Project.OgrenciDers", b =>
                {
                    b.HasOne("Obs_Project.Dersler", "Dersler")
                        .WithMany("OgrenciDers")
                        .HasForeignKey("DersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obs_Project.Ogrenci", "Ogrenciler")
                        .WithMany("OgrenciDers")
                        .HasForeignKey("OgrenciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dersler");

                    b.Navigation("Ogrenciler");
                });

            modelBuilder.Entity("Obs_Project.Dersler", b =>
                {
                    b.Navigation("OgrenciDers");
                });

            modelBuilder.Entity("Obs_Project.Ogrenci", b =>
                {
                    b.Navigation("OgrenciDers");
                });

            modelBuilder.Entity("Obs_Project.Siniflar", b =>
                {
                    b.Navigation("Ogrenciler");
                });
#pragma warning restore 612, 618
        }
    }
}
